# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            guard:
                authenticators:
                    - app.security.login_form_authenticator

            access_denied_handler: app.security.access_denied_handler

            logout:
                path: /logout

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/post/new/, roles: ROLE_ADMIN }
        - { path: ^/post/edit/, roles: ROLE_ADMIN }
